name: Deploy to GitHub Pages

on:
  # Trigger el flujo de trabajo cada vez que hagas push a la rama `master`.
  push:
    branches: [master]
  # Permite ejecutar el flujo de trabajo manualmente desde la pestaña Actions en GitHub.
  workflow_dispatch:

# Permisos necesarios para clonar el repositorio y realizar el despliegue.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2 # Asegúrate de usar una versión compatible de pnpm.

      - name: Install dependencies
        run: pnpm install

      - name: Build your site
        run: pnpm build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist # Cambia "dist" al directorio de salida de tu build si es diferente.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
